### ISSUE TITLE
Bounty: (Fast) Winograd convolutions

### ISSUE THREAD

**Issue by waifairer** [tinygrad/tinygrad#1618]
Current Status:

* Locked by @chaosagent 
* PR: https://github.com/tinygrad/tinygrad/pull/1037

Recent activity:
* Cache buffer loads, merged 2023-08-19 https://github.com/tinygrad/tinygrad/pull/1482
* Better CSE in UOP, merged 2023-08-19 https://github.com/tinygrad/tinygrad/pull/1483

**Comment by waifairer** [comment]
@chaosagent when you get time, could you lay out next steps at a high level?

**Comment by chaosagent** [comment]
https://www.youtube.com/watch?v=jOTfBlKSQYY

**Comment by chaosagent** [comment]
- [ ] cache buffer loads across multiple bufs #1482 
- [ ] cse at uop level #1483 
- [ ] constant folding #1484 (r4r, can use more tests)
- [ ] optimizer.py changes
- [ ] expr_idxs speedup
- [ ] winograd

**Comment by chenyuxyz** [comment]
the compile speed issue is tracking in #1806 , closing this one
