### ISSUE TITLE
make bf16 training work

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#3683]
support changing default_float to bfloat16 and train cifar with bf16

- [x] bf16 Tensor creation and numpy #3724 #3747
- [x] bf16 rand #3764
- [x] move bf16 cast hack out of Tensor.cast #3788 
- [x] direct cast to/from bfloat16 #3903
- [x] train hlb_cifar using bf16 #3905
- [x] bf16 tensor cores #3945
