### ISSUE TITLE
testing and reliability improvements 

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#3805]
- [x] fix assign issue and beautiful_mnist. #3878
- [ ] Add assign spec as tests. #3806  #3807
- [x] fix flaky beam gpt2 test on nvidia benchmark. #3808 #3812 #3817
- [x] issue blocking ring allreduce benchmark script. #3800
- [x] compare optimized kernels with non-optimized ones #3829
- [x] robust BEAM tests in regular CI #3831
- [ ] robust optimizer / training tests in regular CI
- [x] HSA beam child process memory and resource leak #3862
- [x] ~~option to disable SDMA queue in HSA `HSA_ENABLE_SDMA=0`~~
- [x] ~~repro for the HSA transfer hang issue. #3820~~
