### ISSUE TITLE
Scheduler fusion roadmap

### ISSUE THREAD

**Issue by Qazalin** [tinygrad/tinygrad#4323]
- [ ] **Improve reduceop elementwise fusion** (in progress)

- Tests #4321 
- Scheduler changes #4322 

---

- [ ] **Add multi reduce** (in progress)

- Tests #4313
- Linearizer changes: #4320 #4259
- Scheduler changes (pending linearizer completion)
---

- [ ] **Generalize to any graph** (realized reduce, E_)
#4235 #4281

**Comment by chenyuxyz** [comment]
close as finished. feel free to create a new issue
