### ISSUE TITLE
mlperf llama2 70B lora

### ISSUE THREAD

**Issue by ruphail** [tinygrad/tinygrad#4619]
### PART 1 Downloading datasets

1. Sign up to MLcommons to access SCROLLS govreport dataset & model
1.5 Until approval is given to access dataset & model Download llama-2 fused qkv mlpref https://huggingface.co/regisss/llama2-70b-fused-qkv-mlperf & https://www.scrolls-benchmark.com/tasks dataset
##
    BASEDIR=/path/datasets/govreport python3 extra/datasets/scrolls_download.py

### PART 2 Changes to tinygrad core:
- [ ] Implement flash attention in tinybox for training #2955 #1505

### PART 3 Training on tinybox
- [ ] Tune hyper parameters
- [ ] Do a training run on google cloud or locally

```global_batch_size```: 8
```opt_gradient_clip_norm```: 0.3
```lora_dropout```: 0.1
```Sequence_length```: 8196
```lora_alpha```: 32
```weight_decay```: 0.0001
```gradient_accumulation_steps```: 1
```learning_rate_warmup_ratio```: 10000
```learning_rate_training_steps```: 150000
```base_learning_rate```: 0.0001
```Evaluation_batchsize```: 8
```Eval_target```: 0.925

**Comment by geohot** [comment]
What is this supposed to be?
