### ISSUE TITLE
UOpGraph fuzzer

### ISSUE THREAD

**Issue by Qazalin** [tinygrad/tinygrad#4644]
`FUZZ_UOPS=1` sometimes generates wrong toposorts.

These should be builtin to the uops.py graph:
- [x] DEFINE_ACC comes before the outer loop #4656
- [x] Replace priority queue toposort with explicit rule: All nodes between RANGE and PHI are placed inside the loop, everything else is outside.

fuzz_uops.py should handle:
- [x] UOps.DEFINE_GLOBAL order #4651
- [x] Correctly insert UOps.END* #4653
