### ISSUE TITLE
VIZ roadmap to replace all GRAPH tooling

### ISSUE THREAD

**Issue by Qazalin** [tinygrad/tinygrad#6931]
bring VIZ to core tinygrad, replace GRAPH, GRAPHUOPS, SAVE_SCHEDULE, JITGRAPH, etc. (delete all of engine/graph.py)

- [x] Complete rewrite of all of VIZ server
- [x] generic graph_rewrite context tracker
- [ ] Fuzzer running in CI (without slowing CI down too much)
- [ ] Useful UI for both scheduler and uopgraph. important for replacing GRAPH=1
