### ISSUE TITLE
TIP 1 - CONST in big graph

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#8275]
## Abstract

CONST is a well understood UOp, having a dtype and an arg of the value. However, in Tensor, a device and shape are also required, and there's not a straightforward way to add them.

## Motivation

Find a Tensor CONST representation that's amenable to CONST folding using the existing folding rules. This will require

`ADD(CONST(???), CONST(???))`

## Current State

Consts are represented as `VIEW(BUFFER(-1), CONST)`, getting the device from BUFFER and shape from VIEW. An ADD would be `ADD(VIEW(BUFFER(-1), CONST), VIEW(BUFFER(-1), CONST)` and doesn't easily fold.

## Proposal

Firstly, BUFFER(-1) isn't a BUFFER, and should be replaced with a DEVICE(arg=<NAME>) Op.

Then `CONST(VIEW(DEVICE()))` can be a CONST with a Device and shape. This modifies the CONST Op to allow a src. This src is ignored, and CONST always has the value of CONST.

This can't express a masked VIEW, but that's okay. Just use `VIEW(CONST(DEVICE())))`, this is how they are represented in Tensor. The VIEW and CONST will be swapped in rewrite rules.

## Result

`ADD(CONST(VIEW(DEVICE())), CONST(VIEW(DEVICE())))` will fold as expected to `CONST(VIEW(DEVICE()))`

## Alternatives

Potentially, we could just use `CONST` and assume the shape and device come from elsewhere. But this has several issues.

1) What is the shape and device of the Tensor? All Tensors must have shape and device.
2) These UOps won't have ShapeTrackers, so `.st` will return None.
3) If all become CONST, the output won't have a shape.

This seems a lot harder to reason about as things are not local. A key principle of UOps is that you want things to have their full meaning locally. The `CONST(VIEW(DEVICE()))` has very little downside too, all CONST srcs can be rewritten to nothing once we are in a kernel.

## Work Items

- [x] Replace BUFFER(-1) with DEVICE
- [x] Replace `VIEW(DEVICE, CONST)` with `VIEW(CONST(DEVICE()))` in Tensor const creation.
- [x] Add rewrite rule to rewrite `VIEW(CONST(DEVICE()))` to `CONST(VIEW(DEVICE()))` if the view is unmasked
- [x] Add in normal constant folding, observe that it works.

**Comment by Qazalin** [comment]
1. does CONST look like:
```
UOp(Ops.EXPAND, dtypes.float, arg=(45, 65), src=(
  UOp(Ops.RESHAPE, dtypes.float, arg=(1, 1), src=(
    UOp(Ops.CONST, dtypes.float, arg=0.0, src=(
      UOp(Ops.DEVICE, arg='GPU'),
      UOp(Ops.VIEW, dtypes.void, arg=ShapeTracker(views=(View(shape=(), strides=(), offset=0, mask=None, contiguous=True),)), src=()),)),)),))
```
or
```
UOp(Ops.CONST, dtypes.float, arg=0.0, src=(
  UOp(Ops.DEVICE, arg='GPU'),
  UOp(Ops.VIEW, dtypes.void, arg=ShapeTracker(views=(View(shape=(45, 65), strides=(0, 0), offset=0, mask=None, contiguous=False),)), src=()),))
```

2. What if it's wrapped around a VIEW but unmasked? what about symbolic shape? Does UPat.cvar match
VIEW(CONST) + VIEW(CONST)?
Otherwise I'd add "early unmasked, non-symbolic shape (?) merge view for CONST" to work items

3. What if your CONST folding happens late? CONST doesn't have a device src, it has the BUFFER src of that op. Is this fine?
![image](https://github.com/user-attachments/assets/18c3f4d6-843b-4c82-a43d-f2eca620c536)

4. Should also note that this is unacceptable:
![image](https://github.com/user-attachments/assets/15e7565a-ba3f-4c46-ab8d-335ca08d8330)
we should assert that the VIEW src in CONST is unmasked. (but re:1, EXPAND is fine)

**Comment by Qazalin** [comment]
1. The first one doesn't match UPat.cvar, it should. CONST(32, 32) + CONST(32, 32) should still fold.
2. How does BIND look like?
```
UOp(Ops.BIND, dtypes.int, arg=None, src=(
  UOp(Ops.DEVICE, arg='gpu'),
  UOp(Ops.VIEW, dtypes.void, arg=ShapeTracker(views=(View(shape=(), strides=(), offset=0, mask=None, contiguous=True),)), src=()),
  UOp(Ops.DEFINE_VAR, dtypes.int, arg=('i', 1, 10), src=()),
  UOp(Ops.CONST, dtypes.int, arg=1, src=()),))
```

**Comment by geohot** [comment]
So this is blocked on CONST folding happening before bufferization.

**Comment by Qazalin** [comment]
tensor_uop that is const folded late doesn't realize.
```
a = (Tensor([1, 2, 3, 4,]) * 0).realize()
print(a.lazydata.base.realized) # None
```
This means we can collapse the BUFFER uop tracking back to a late CONST folded op.
Example: a <tensor_uop> * 0 gets rewritten to:

```diff
- VIEW(BUFFER(DEVICE), <mul>)
+ VIEW(BUFFER(DEVICE), CONST)
```

first, then you can delete the BUFFER from CONST.

```diff
- VIEW(BUFFER(DEVICE), CONST)
+ VIEW(DEVICE, CONST)
```

I think collapsing the BUFFER is the correct way to do this.

**Comment by Qazalin** [comment]
upstream completed in 3 diffs:
#8355
#8389 
#8419
also allowed cleanups: #8390+#8391

-26 lines total.
