### ISSUE TITLE
TIP 2 - Buffer allocation behavior of COPY, EMPTY and BUFFER_VIEW

### ISSUE THREAD

**Issue by Qazalin** [tinygrad/tinygrad#8282]
## Abstract

By default, if two Tensors do the same operation, we dedup the underlying Tensor UOp:

```
x = a+b
y = a+b
assert x is not y
assert x.lazydata is y.lazydata
```

If we call `x.realize()`, both x and y get allocated the same device Buffer:

```
x.realize()
print(x.lazydata.realized) # <buf real:True device:GPU size:1024 dtype:dtypes.float offset:0>
assert x.lazydata.realized is y.lazydata.realized
```

However, there are three special `Ops`—we call them GroupOp.Meta— that always get allocated a new Buffer upon creation:

https://github.com/tinygrad/tinygrad/blob/5755ac1f7286822fd557fd13820317980ee8602d/tinygrad/ops.py#L99-L100

```
a = Tensor.randn(32, 32, device="GPU")
b = a.to("CLANG")
c = a.to("CLANG")
assert b.lazydata is not c.lazydata
```

This TIP specifies a structure for GroupOp.Meta Ops that accommodates this deduping behavior.

## Motivation

All UOp structures should be created such that they contain the full context locally (in the sources).
The worst case is when the meaning of a UOp depends on its children. For example, if COPY does not contain a DEVICE in its ancestors, a single `COPY` UOp cannot function as a standalone, meaningful part of the AST without a child that defines its DEVICE.
We need a way to make every UOp instance of COPY unique while also preserving complete locality.

## Current state

The 3 Ops that are do not follow the default deduping behavior are:

1. `COPY`: Copies a Buffer to a new Buffer, it can output to the same device (clone) or a new device.
2. `EMPTY`: Allocates a piece of memory on the device given a size.
3. `BUFFER_VIEW`: Creates a subbuffer (offset buffer) of its parent's Buffer. (for seeing where it's used, [refer to tensor_uop_spec](https://github.com/tinygrad/tinygrad/blob/5755ac1f7286822fd557fd13820317980ee8602d/tinygrad/engine/schedule.py#L83-L92))

_(the examples provided use EMPTY since it's the cleanest to print, but everything below applies to COPY and BUFFER_VIEW as well.)_

Currently, the BUFFER and ShapeTracker of an EMPTY UOp come from its children:

```
>> print(Tensor.empty(4).lazydata)

UOp(Ops.VIEW, dtypes.float, arg=ShapeTracker.from_shape((4,), src=(
  UOp(Ops.BUFFER, dtypes.float, arg=(0, 4), src=(
    UOp(Ops.DEVICE, dtypes.void, arg='GPU', src=()),)),
  UOp(Ops.EMPTY, dtypes.float, arg=None, src=()),))
```

## Proposal

We give all MetaOps a new VIEW(BUFFER) in src[0]:

```
UOp(Ops.EMPTY, dtypes.float, arg=None, src=(
  UOp(Ops.VIEW, dtypes.float, arg=ShapeTracker(views=(View(shape=(4,), strides=(1,), offset=0, mask=None, contiguous=True),)), src=(
    UOp(Ops.BUFFER, dtypes.float, arg=(0, 4), src=(
      UOp(Ops.DEVICE, dtypes.void, arg='GPU', src=()),)),)),))
```

Every time a meta op is created, we construct a new BUFFER UOp and add it to the first source.

```
print(Tensor.empty(4).lazydata.buf_uop) # UOp(Ops.BUFFER, ..., (0, 4))
print(Tensor.empty(4).lazydata.buf_uop) # UOp(Ops.BUFFER, ..., (1, 4))
assert Tensor.empty(4).lazydata.buffer is not Tensor.empty(4).lazydata.buffer
```

## Work Items

- [x] Add Ops.DEVICE, first as src of BUFFER
- [x] Refactor UOp.metaop construction from VIEW(BUFFER, COPY) -> COPY(DEVICE, src)
- [ ] Refactor EMPTY construction from VIEW(BUFFER, EMPTY) -> EMPTY(VIEW(BUFFER))
- [ ] Refactor BUFFER_VIEW construction from VIEW(BUFFER, BUFFER_VIEW) to just BUFFER_VIEW(src) - as a start - long-term we would like to delete it from the Ops layer.

**Comment by geohot** [comment]
I don't think DEVICE should be a src of BUFFER. It doesn't make sense, the BUFFER is actually on the device.

**Comment by geohot** [comment]
I had wrongly thought about how deduping would work. I do like DEVICE as BUFFER src.

**Comment by Qazalin** [comment]
Yeah moving BUFFER init to schedule means COPY isn't deduped if it's the same srcs.

Presented the option because `TestTensorUopRepresentation.test_copyin` states it's "an extra buffer".

We can move forward with Ops.DEVICE then, `VIEW(BUFFER(DEVICE), COPY)`.

**Comment by Qazalin** [comment]
Results:

1. COPY is now COPY(DEVICE, copyin) and is always deduped https://github.com/tinygrad/tinygrad/pull/8506

2. EMPTY op has been deleted! https://github.com/tinygrad/tinygrad/pull/8544 - It is now just composing VIEW(BUFFER).

3. BUFFER_VIEW is refactored to not have a BUFFER source. It is simply a BUFFER_VIEW(src). The ShapeTracker is computed in the st cached_property instead of a VIEW op. https://github.com/tinygrad/tinygrad/pull/8540

note on BUFFER_VIEW: we can always go back to working on "delete BUFFER_VIEW op". Moving all subbuffer rewrites to si_lowerer is the long-term solution https://github.com/tinygrad/tinygrad/pull/8473.
